version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: username
  MYSQL_PASSWORD: password
  MYSQL_DATABASE: sampledb

services:
  mysql-db:
    image: mariadb:10.11.3-jammy
    container_name: todo_mysql_container
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    expose:
      - 3306
  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin/phpmyadmin
    container_name: todo_phpadmin_container
    environment:
      PMA_HOST: mysql-db
    links:
      - mysql-db:mysql-db
    ports:
      - 5001:80
  api:
    build: ./api
    container_name: todo_api_container
    depends_on:
      - mysql-db
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql-db
      FLASK_DEBUG: 1
      DEBUG: 1
    ports:
      - 5000:5000
    volumes:
      - ./api:/app:ro
    links:
      - mysql-db:mysql-db
  web:
    build: ./web
    container_name: todo_web_container
    ports:
      - 5003:5003
    volumes:
      - ./web/src:/app/src:ro